# Inserts a blank line between shell prompts
add_newline = true

format = """$all$git_branch$git_status$character"""


[character]
success_symbol = "[ï”ï”](bold green)"
error_symbol = "[âœ—ï”ï”](bold red) "
vicmd_symbol = "[ï“ï“](bold green) "


[package]
disabled = true
symbol = "pkg "


[battery]
full_symbol = "ï®£ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ðŸ’€ "


[cmd_duration]
min_time = 100
format = " took [$duration](bold yellow)"


[[battery.display]]
threshold = 10
style = "bold red"


[directory]
format = "[ï„” $path]($style)[$read_only]($read_only_style) "
style = "bold blue"


[git_branch]
format = "[$branch]($style) "
symbol = "îœ¥ "

[git_status]
format = '([{$all_status$ahead_behind}]($style) )'
style = "bold red"
ahead = ">"
behind = "<"
diverged = "<>"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "r"
deleted = "x"
disabled = false


[aws]
symbol = "aws "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[rust]
symbol = "rs "
style = "bold #F88A3E"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[golang]
symbol = "go "
style = "bold #70D1EA"

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[perl]
symbol = "pl "

[php]
symbol = "php "

[purescript]
symbol = "purs "

[python]
symbol = "py "
style = "bold #78EDC5"

[ruby]
symbol = "rb "

[scala]
symbol = "scala "

[swift]
symbol = "swift "
